# //javascript code
#     var contenOfNews = _news.dataContent.replace(/<Origin.*?<\/Origin>/g,'');
#     contenOfNews = contenOfNews.replace(/&gt;/g,'');
#     contenOfNews = contenOfNews.replace(/<\/?pre>/g,'');
#     contenOfNews = contenOfNews.replace(/\s\n(?!\s)/g,' ');
#     var newsP = contenOfNews.split(/\s\n\s/);
#     contenOfNews = newsP.filter(function(p){return p!=''}).map(function(p){return '<p>'+p+'</p>'}).join('');
#     _news.dataContent = contenOfNews

import re
line = "QuoteRefNBHI* reuters://realtime/verb=Open/url=cpurl://apps.cp./Apps/cb-polls?RIC=HUINT%3DECI  Reuters Hungary central bank rate forecasts     * reuters://realtime/verb=Open/url=cpurl://apps.cp./Apps/econ-polls?RIC=HUCPIAP%3DECI  Reuters Hungary average inflation forecasts     * reuters://realtime/verb=Open/url=cpurl://apps.cp./Apps/econ-polls?RIC=HUGDPAP%3DECI  Reuters Hungary GDP forecasts      By Krisztina  Than and Sandor Peto     BUDAPEST, July 20 (Reuters) - Hungary&apos;s central bank is expected to keep its main interest rate on hold on July 26 after last week embarking on further unconventional easing by reducing local banks&apos; opportunities to park funds in its three-month deposits.     All 17 analysts in a July 18-20 Reuters poll said the National Bank of Hungary would hold fire at its meeting next Tuesday after promising in May that it had finished its rate cuts.     Just last week the central bank announced steps aimed at nudging banks to offer cheaper loans to households and companies and to buy up government debt.     \"The NBH won&apos;t change its base rate. Its intention is to loosen monetary stance via unconventional easing,\" said Peter Virovacz, an analyst at ING.     The central bank said last week that tenders for three-month deposits would be held once a month from August rather than weekly, and that from Oct. 26 it will impose restrictions on the amount banks can deposit.     Short-term government debt yields have plunged as a result of the new measure, with three-month treasury bills sold at 0.6 percent at Tuesday&apos;s auction, down from 0.8 percent at the previous auction, and well below the central bank&apos;s base rate of 0.9 percent.        The median forecast in the poll suggested no change in the central bank&apos;s base rate until the end of 2017. By the end of 2018, analysts see the base rate rising to 1.25 percent.     The bank, led by Gyorgy Matolcsy, a strong ally of Prime Minister Viktor Orban, has slashed its base rate from a 2012 peak of 7 percent to just 0.9 percent and launched a massive funding for growth programme in 2013, all aimed at aiding the economy.     The bank said there was excess liquidity parked at the central bank and it wanted to channel those funds into lending and into the government debt market.     Deputy Governor Marton Nagy has said that both interbank rates and government debt yields could fall as the new regime takes effect.     \"The adjustment has started at the banks,\" said Gabor Nemeth, a portfolio manager at Aegon.     \"The role of cash products like short-term discount treasury bills will appreciate in banks&apos; liquidity management, therefore yields have started to fall.\"    (Additional reporting by Marton Dunai; Editing by Hugh Lawson)  ((sandor.peto@thomsonreuters.com; +36 1 327 4744; Reuters Messaging: sandor.peto.thomsonreuters.com@reuters.net))  Keywords: HUNGARY RATES/POLL"
contenOfNews = re.sub(r"http[s]|[a-zA-z]+?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+|[\w\.-]+@[\w\.-]+", "", line)
print(contenOfNews)
